// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"beyond/test/internal/logic"
	"beyond/test/internal/svc"
	"beyond/test/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Articles(ctx context.Context, in *pb.ArticlesRequest) (*pb.ArticlesResponse, error) {
	l := logic.NewArticlesLogic(ctx, s.svcCtx)
	return l.Articles(in)
}
